services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: enzzo
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mybase
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      my_network:
        ipv4_address: 192.168.1.105
    restart: always

  web:
    build:
      context: ./app
    container_name: app_container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
      DATABASE_URL: "postgresql://enzzo:123456@192.168.1.105:5432/mybase"
    depends_on:
      - postgres
    networks:
      my_network:
        ipv4_address: 192.168.1.106
    restart: always

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
